# Generated by Django 4.2.3 on 2023-07-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_userinfo_create_time_alter_userinfo_depart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=50, verbose_name='手机号')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('level', models.IntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级'), (4, '四级')], verbose_name='级别')),
                ('status', models.IntegerField(choices=[(1, '未占用'), (2, '已占用')], verbose_name='状态')),
            ],
        ),
    ]
