# Generated by Django 4.2.3 on 2023-07-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mobile',
            new_name='PrettyNum',
        ),
    ]
